### ISSUE TITLE
Downloading segments too slow

### ISSUE THREAD

**Issue by dmkenza** [glubsy/livestream_saver#29] opened 2021-12-03 16:17 UTC
Downloading segments are too slow in current version.
In previous versions it was fast.
First step for downloading already existed stream takes a lot of time. So author can be on time to close and delete his steam.

Check this please.

**Comment by dmkenza** [comment] 2021-12-03 16:23
In my old version of Livesaver downloading is slow too =(

![123](https://user-images.githubusercontent.com/66675746/144636859-b1b2983c-fbaa-4843-9048-5997a57de500.png)
t.

**Comment by glubsy** [comment] 2021-12-03 17:01
I'm aware of the issue, and I'm working on a workaround currently based on concurrent segment download. This is Youtube servers throttling the bandwidth.

yt-dlp has a working workaround so you could use that in the meantime (you can also call yt-dlp with the on-download hook).

This is a duplicate of #11.

**Closed by glubsy** 2021-12-03 17:01 UTC
